### PR TITLE
chore: upgrade rand to 0.8 + dev dependencies

### PR DESCRIPTION
**Pull request by audunhalland**

### CODE REVIEW

**Comment by kennytm** [comment]
Please update the two failed tests, thanks.

**Comment by audunhalland** [comment]
it's the same two tests that has failed on the master branch though (so no regression I believe). but yes, I could try to fix them

**Comment by audunhalland** [comment]
tests updated. I've just changed the expected values to make them pass, you should probably double check it.

**Review by kennytm — APPROVED** [review]

**Comment by kennytm** [comment]
Published as 0.15.0.

**Pull request merged**
